name: "Run Cypress BDD Tests"

on:
  workflow_dispatch:  # Uruchamianie ręczne
  push:
    branches:
      - new_cypress_tests  # Uruchamiaj testy tylko na tej gałęzi

jobs:
  cypress-bdd-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.13.0-chrome-132.0.6834.83-1-ff-134.0.1-edge-131.0.2903.147-1
      options: --user 1001

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Pobiera kod repozytorium

      - name: Set up Yarn
        run: yarn set version stable # Upewnia się, że Yarn jest dostępny

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install missing peer dependencies
        run: yarn add -D @babel/preset-env babel-loader esbuild

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run Cypress BDD Tests
        uses: cypress-io/github-action@v6
        with:
          start: ""  # Nie uruchamia serwera, aplikacja działa już pod adresem URL
          wait-on: "http://localhost:3000"  # Czeka na dostępność aplikacji
          wait-on-timeout: 90  # Wydłużony timeout do 90 sekund, aby uniknąć błędów
          bro
